name: Deploy Website

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy static website to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::443245369180:role/cloudpipe-deploy-github-actions-deploy-role
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Deploy website files to S3
        run: |
          aws s3 sync website/ s3://cloudpipe-deploy-443245369180-us-east-1 --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id EPYW7W32NW95W \
            --paths "/*"

      - name: Deployment complete
        run: echo "CloudPipe website deployed successfully."